# ** THIS NOTEBOOK IS A GARDEN OF EXPLORATION **
                      *** DRAFT of the 01_MARKET_ANALYSIS_AND_SILVENCY_SCOPING ***

## 01 - EDA OF ValeurFonciere-2025
In order to share in the main jupyter notebook the code the most relevant for the understanding and keeping track the topic

In [5]:
# 🇬🇧 Expert Audit: Loading raw DVF data for inspection
# 🇫🇷 Audit Expert : Chargement des données DVF brutes pour inspection

import pandas as pd

# 1. Utilisation de nrows=100 pour une lecture instantanée
# 2. low_memory=False pour éviter les erreurs de type de colonnes
# 3. sep=',' ou '|' (vérifie ton fichier, souvent c'est la virgule ou la barre verticale)

df_audit = pd.read_csv(
    '../data/raw/ValeursFoncieres-2025-S1.txt',
    # nrows=100, 
    sep='|', 
    low_memory=False
)

# Affichage des colonnes pour voir "l'inventaire"
print(df_audit.columns.tolist())

['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot', '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot', 'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local', 'Surface reelle bati', 'Nombre pieces principales', 'Nature culture', 'Nature culture speciale', 'Surface terrain']

In [6]:
df_audit.head()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,78.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,1.0,Maison,NaN,111.0,5.0,S,NaN,133.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,3.0,Dépendance,NaN,0.0,0.0,S,NaN,133.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,46.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,17.0

In [7]:
def check_data_quality(df_audit):

    print(f"Format du DataFrame (rows, cols): {df_audit.shape}\n")
    
    # Création d'un tableau récapitulatif
    stats = pd.DataFrame({
        'Type': df_audit.dtypes,
        'Manquants': df_audit.isna().sum(),
        '% Manquants': (df_audit.isna().sum() / len(df_audit) * 100).round(2),
        'Uniques': df_audit.nunique(),
        'Doublons (par colonne)': df_audit.apply(lambda x: x.duplicated().sum())
        
    })
    
    return stats
check_data_quality (df_audit)

Format du DataFrame (rows, cols): (1387077, 43)

,Type,Manquants,% Manquants,Uniques,Doublons (par colonne)
Identifiant de document,float64,1387077,100.00,0,1387076
Reference document,float64,1387077,100.00,0,1387076
1 Articles CGI,float64,1387077,100.00,0,1387076
2 Articles CGI,float64,1387077,100.00,0,1387076
3 Articles CGI,float64,1387077,100.00,0,1387076
4 Articles CGI,float64,1387077,100.00,0,1387076
5 Articles CGI,float64,1387077,100.00,0,1387076
No disposition,int64,0,0.00,43,1387034
Date mutation,str,0,0.00,173,1386904
Nature mutation,str,0,0.00,6,1387071
Valeur fonciere,str,13995,1.01,71189,1315887
No voie,float64,513979,37.05,5784,1381292
B/T/Q,str,1322557,95.35,39,1387037
Type de voie,str,542232,39.09,126,1386950
Code voie,str,12158,0.88,13877,1373199
Voie,str,12171,0.88,234661,1152415
Code postal,float64,12231,0.88,5857,1381219
Commune,str,0,0.00,28603,1358474
Code departement,str,0,0.00,97,1386980
Code commune,int64,0,0.00,900,1386177
Prefixe de section,float64,1316580,94.92,735,1386341
Section,str,56,0.00,576,1386500
No plan,int64,0,0.00,5703,1381374
No Volume,str,1384014,99.78,283,1386793
1er lot,str,944993,68.13,5604,1381472
Surface Carrez du 1er lot,str,1251644,90.24,13817,1373259
2eme lot,str,1248916,90.04,2629,1384447
Surface Carrez du 2eme lot,str,1342513,96.79,8712,1378364
3eme lot,str,1361188,98.13,795,1386281
Surface Carrez du 3eme lot,str,1381838,99.62,1871,1385205
4eme lot,float64,1376995,99.27,420,1386656
Surface Carrez du 4eme lot,str,1385365,99.88,508,1386568
5eme lot,float64,1381027,99.56,282,1386794
Surface Carrez du 5eme lot,str,1386317,99.95,181,1386895
Nombre de lots,int64,0,0.00,56,1387021
Code type local,float64,572338,41.26,4,1387072
Type local,str,572338,41.26,4,1387072
Identifiant local,float64,1387077,100.00,0,1387076
Surface reelle bati,float64,573187,41.32,2733,1384343
Nombre pieces principales,float64,573187,41.32,36,1387040
Nature culture,str,447624,32.27,27,1387049
Nature culture speciale,str,1325533,95.56,121,1386955
Surface terrain,float64,447624,32.27,32316,1354760

In [19]:
df_audit['Nature mutation'].value_counts()

Nature mutation
Vente                                 1310710
Vente en l'état futur d'achèvement      55448
Echange                                 16859
Vente terrain à bâtir                    2881
Adjudication                              928
Expropriation                             251
Name: count, dtype: int64

In [28]:
print(df_audit['Nature mutation'].value_counts())

Nature mutation
Vente                                 1310710
Vente en l'état futur d'achèvement      55448
Echange                                 16859
Vente terrain à bâtir                    2881
Adjudication                              928
Expropriation                             251
Name: count, dtype: int64

In [34]:
# Relevant filtering of real estate transactions
mutations_cibles = [
    'Vente', 
    "Vente en l'état futur d'achèvement", 
    'Vente terrain à bâtir'
]

# Filtring the DataFrame to keep only relevant real estate transactions
df_etude = df_audit[df_audit['Nature mutation'].isin(mutations_cibles)].copy()
# Summary of filtering
print(f"Volume initial : {len(df_audit)}")
print(f"Volume après filtrage : {len(df_etude)}")
print(f"Lignes supprimées : {len(df_audit) - len(df_etude)}")
# Aperçu des types de mutations restants
print("\nRépartition après filtrage :")
print(df_etude['Nature mutation'].value_counts())

Volume initial : 1387077
Volume après filtrage : 1369039
Lignes supprimées : 18038

Répartition après filtrage :
Nature mutation
Vente                                 1310710
Vente en l'état futur d'achèvement      55448
Vente terrain à bâtir                    2881
Name: count, dtype: int64

In [36]:
print(df_etude['Nature culture'].value_counts())

Nature culture
S     451122
T     134275
P      74130
J      45432
BT     43107
L      37187
AG     36121
AB     30466
VI     14778
BR     13827
VE     10664
BS      7299
PA      6971
B       4817
E       3626
BP      3435
BF      2184
PP      1012
PC       689
PH       571
BM       554
CH       392
CA       322
LB       106
PE        68
TP        64
BO        28
Name: count, dtype: int64

In [56]:
# 1. Définition des codes à haut potentiel
nature_cibles = ['S', 'L', 'J', 'BR']

# 2. Création du DataFrame filtré
df_immo = df_etude[df_etude['Nature culture'].isin(nature_cibles)].copy()

# 3. CORRECTION : On nettoie la colonne SANS écraser tout le DataFrame
df_immo['Nature culture'] = df_immo['Nature culture'].astype(str).str.strip()

# 4. Rapport de l'auditeur (Maintenant stats_culture fonctionnera !)
print("--- Analyse du Gisement Foncier Social ---")
stats_culture = df_immo['Nature culture'].value_counts()

for code, count in stats_culture.items():
    pct = (count / len(df_immo) * 100)
    print(f"Code {code}: {count} parcelles ({round(pct, 2)}%)")

print(f"\nTotal parcelles exploitables pour le projet : {len(df_immo)}")

--- Analyse du Gisement Foncier Social ---
Code S: 451122 parcelles (82.39%)
Code J: 45432 parcelles (8.3%)
Code L: 37187 parcelles (6.79%)
Code BR: 13827 parcelles (2.53%)

Total parcelles exploitables pour le projet : 547568

In [ ]:
check_data_quality (df_immo)

Format du DataFrame (rows, cols): (547568, 43)

,Type,Manquants,% Manquants,Uniques,Doublons (par colonne)
Identifiant de document,float64,547568,100.00,0,547567
Reference document,float64,547568,100.00,0,547567
1 Articles CGI,float64,547568,100.00,0,547567
2 Articles CGI,float64,547568,100.00,0,547567
3 Articles CGI,float64,547568,100.00,0,547567
4 Articles CGI,float64,547568,100.00,0,547567
5 Articles CGI,float64,547568,100.00,0,547567
No disposition,int64,0,0.00,13,547555
Date mutation,object,0,0.00,169,547399
Nature mutation,object,0,0.00,3,547565
Valeur fonciere,object,7447,1.36,35403,512164
No voie,float64,157527,28.77,5142,542425
B/T/Q,object,519913,94.95,39,547528
Type de voie,object,180173,32.90,116,547451
Code voie,object,0,0.00,10148,537420
Voie,object,2,0.00,132727,414840
Code postal,float64,46,0.01,5845,541722
Commune,object,0,0.00,26442,521126
Code departement,object,0,0.00,97,547471
Code commune,int64,0,0.00,894,546674
Prefixe de section,float64,522904,95.50,715,546852
Section,object,24,0.00,554,547013
No plan,int64,0,0.00,4891,542677
No Volume,object,547568,100.00,0,547567
1er lot,object,545889,99.69,179,547388
Surface Carrez du 1er lot,object,547000,99.90,369,547198
2eme lot,object,547568,100.00,0,547567
Surface Carrez du 2eme lot,object,547568,100.00,0,547567
3eme lot,object,547568,100.00,0,547567
Surface Carrez du 3eme lot,object,547568,100.00,0,547567
4eme lot,float64,547568,100.00,0,547567
Surface Carrez du 4eme lot,object,547568,100.00,0,547567
5eme lot,float64,547568,100.00,0,547567
Surface Carrez du 5eme lot,object,547568,100.00,0,547567
Nombre de lots,int64,0,0.00,2,547566
Code type local,float64,181370,33.12,4,547563
Type local,object,181370,33.12,4,547563
Identifiant local,float64,547568,100.00,0,547567
Surface reelle bati,float64,182010,33.24,2550,545017
Nombre pieces principales,float64,182010,33.24,34,547533
Nature culture,object,0,0.00,4,547564
Nature culture speciale,object,516841,94.39,37,547530
Surface terrain,float64,0,0.00,12661,534907

In [64]:
print (df_immo.columns.tolist())

['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot', '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot', 'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local', 'Surface reelle bati', 'Nombre pieces principales', 'Nature culture', 'Nature culture speciale', 'Surface terrain']

In [76]:
# 1. Liste des colonnes à supprimer (ton "bruit" administratif)
colonnes_a_supprimer = [
    'Identifiant de document', 'Reference document', 
    '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 
    'No Volume', 'No plan',
    '1er lot', 'Surface Carrez du 1er lot', 
    '2eme lot', 'Surface Carrez du 2eme lot', 
    '3eme lot', 'Surface Carrez du 3eme lot',
    '4eme lot', 'Surface Carrez du 4eme lot', 
    '5eme lot', 'Surface Carrez du 5eme lot', 'Nature culture speciale', 'Identifiant local', 'Prefixe de section', 'B/T/Q', 
    'No voie', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Nombre pieces principales','Section','No disposition'
]

# 2. Suppression sécurisée
# errors='ignore' permet d'éviter un plantage si une colonne a déjà été supprimée
df_immo = df_immo.drop(columns=colonnes_a_supprimer, errors='ignore')

# 3. Rapport de l'auditeur
print(f"✅ Nettoyage effectué. Colonnes restantes : {len(df_immo.columns)}")
print(df_immo.columns.tolist())

✅ Nettoyage effectué. Colonnes restantes : 12
['Date mutation', 'Nature mutation', 'Valeur fonciere', 'Commune', 'Code departement', 'Code commune', 'Nombre de lots', 'Code type local', 'Type local', 'Surface reelle bati', 'Nature culture', 'Surface terrain']

In [77]:
df_immo.head()

,Date mutation,Nature mutation,Valeur fonciere,Commune,Code departement,Code commune,Nombre de lots,Code type local,Type local,Surface reelle bati,Nature culture,Surface terrain
0,07/01/2025,Vente,"468000,00",FARGES,01,158,0,NaN,NaN,NaN,J,78.0
1,07/01/2025,Vente,"468000,00",FARGES,01,158,0,1.0,Maison,111.0,S,133.0
2,07/01/2025,Vente,"468000,00",FARGES,01,158,0,3.0,Dépendance,0.0,S,133.0
3,06/01/2025,Vente,"180000,00",MONTANGES,01,257,0,NaN,NaN,NaN,S,46.0
4,06/01/2025,Vente,"180000,00",MONTANGES,01,257,0,NaN,NaN,NaN,J,17.0

In [78]:
check_data_quality (df_immo)

Format du DataFrame (rows, cols): (547568, 12)

,Type,Manquants,% Manquants,Uniques,Doublons (par colonne)
Date mutation,object,0,0.00,169,547399
Nature mutation,object,0,0.00,3,547565
Valeur fonciere,object,7447,1.36,35403,512164
Commune,object,0,0.00,26442,521126
Code departement,object,0,0.00,97,547471
Code commune,int64,0,0.00,894,546674
Nombre de lots,int64,0,0.00,2,547566
Code type local,float64,181370,33.12,4,547563
Type local,object,181370,33.12,4,547563
Surface reelle bati,float64,182010,33.24,2550,545017
Nature culture,object,0,0.00,4,547564
Surface terrain,float64,0,0.00,12661,534907

In [79]:
print (df_immo.columns.tolist())

['Date mutation', 'Nature mutation', 'Valeur fonciere', 'Commune', 'Code departement', 'Code commune', 'Nombre de lots', 'Code type local', 'Type local', 'Surface reelle bati', 'Nature culture', 'Surface terrain']

## 02 exploration

In [2]:
import pandas as pd

# 1. Utilisation de nrows=100 pour une lecture instantanée
# 2. low_memory=False pour éviter les erreurs de type de colonnes
# 3. sep=',' ou '|' (vérifie ton fichier, souvent c'est la virgule ou la barre verticale)

In [29]:
df_ips_ = pd.read_csv('../data/raw/02_fr-en-ips-ecoles-ap2022.csv', sep=';')
df_income_ = pd.read_csv('../data/raw/02_FILO2021_DISP_COM.csv', sep=';', encoding='latin-1')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17288\1423481474.py:2: DtypeWarning: Columns (0: CODGEO) have mixed types. Specify dtype option on import or set low_memory=False.
  df_income_ = pd.read_csv('../data/raw/02_FILO2021_DISP_COM.csv', sep=';', encoding='latin-1')

In [30]:
check_data_quality (df_ips_)

Format du DataFrame (rows, cols): (97080, 23)

,Type,Manquants,% Manquants,Uniques,Doublons (par colonne)
num_ligne,float64,0,0.00,97080,0
Rentrée scolaire,str,0,0.00,3,97077
Code région,int64,0,0.00,18,97062
Région,str,0,0.00,18,97062
Code de l'académie,int64,0,0.00,30,97050
Académie,str,0,0.00,30,97050
Code du département,str,0,0.00,101,96979
Département,str,0,0.00,104,96976
Code INSEE de la commune,str,0,0.00,18324,78756
Nom de la commune,str,0,0.00,17766,79314
UAI,str,0,0.00,33004,64076
Nom de l'établissement,str,0,0.00,18238,78842
Secteur,str,0,0.00,2,97078
IPS,str,0,0.00,978,96102
IPS national privé,float64,0,0.00,3,97077
IPS national public,float64,0,0.00,2,97078
IPS national,float64,0,0.00,3,97077
IPS académique privé,float64,374,0.39,69,97010
IPS académique public,float64,0,0.00,69,97011
IPS académique,float64,0,0.00,73,97007
IPS départemental privé,float64,374,0.39,189,96890
IPS départemental public,float64,0,0.00,150,96930
IPS départemental,float64,0,0.00,159,96921

In [31]:
df_ips_

,num_ligne,Rentrée scolaire,Code région,Région,Code de l'académie,Académie,Code du département,Département,Code INSEE de la commune,Nom de la commune,...,IPS,IPS national privé,IPS national public,IPS national,IPS académique privé,IPS académique public,IPS académique,IPS départemental privé,IPS départemental public,IPS départemental
0,40004.0,2023-2024,16,OCCITANIE,16,TOULOUSE,31,HAUTE-GARONNE,31147,CLARAC,...,NS,120.3,102.9,105.5,119.8,108.4,109.9,133.6,114.3,116.2
1,40011.0,2023-2024,16,OCCITANIE,16,TOULOUSE,31,HAUTE-GARONNE,31157,CUGNAUX,...,115.6,120.3,102.9,105.5,119.8,108.4,109.9,133.6,114.3,116.2
2,40012.0,2023-2024,16,OCCITANIE,16,TOULOUSE,31,HAUTE-GARONNE,31159,LE CUING,...,97.8,120.3,102.9,105.5,119.8,108.4,109.9,133.6,114.3,116.2
3,40013.0,2023-2024,16,OCCITANIE,16,TOULOUSE,31,HAUTE-GARONNE,31160,DAUX,...,130.3,120.3,102.9,105.5,119.8,108.4,109.9,133.6,114.3,116.2
4,40017.0,2023-2024,16,OCCITANIE,16,TOULOUSE,31,HAUTE-GARONNE,31165,EAUNES,...,106.2,120.3,102.9,105.5,119.8,108.4,109.9,133.6,114.3,116.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97075,12485.0,2022-2023,17,PAYS DE LA LOIRE,17,NANTES,44,LOIRE-ATLANTIQUE,44143,REZE,...,120.5,119.3,102.9,105.4,112.0,104.5,107.2,118.1,110.6,113.2
97076,12486.0,2022-2023,17,PAYS DE LA LOIRE,17,NANTES,44,LOIRE-ATLANTIQUE,44143,REZE,...,122.2,119.3,102.9,105.4,112.0,104.5,107.2,118.1,110.6,113.2
97077,12488.0,2022-2023,17,PAYS DE LA LOIRE,17,NANTES,44,LOIRE-ATLANTIQUE,44144,RIAILLE,...,102.6,119.3,102.9,105.4,112.0,104.5,107.2,118.1,110.6,113.2
97078,12496.0,2022-2023,17,PAYS DE LA LOIRE,17,NANTES,44,LOIRE-ATLANTIQUE,44155,SAINT COLOMBAN,...,111.8,119.3,102.9,105.4,112.0,104.5,107.2,118.1,110.6,113.2
97079,12498.0,2022-2023,17,PAYS DE LA LOIRE,17,NANTES,44,LOIRE-ATLANTIQUE,44161,SAINT GILDAS DES BOIS,...,92.7,119.3,102.9,105.4,112.0,104.5,107.2,118.1,110.6,113.2

In [35]:
df_ips_.columns.tolist()

['num_ligne',
 'Rentrée scolaire',
 'Code région',
 'Région',
 "Code de l'académie",
 'Académie',
 'Code du département',
 'Département',
 'Code INSEE de la commune',
 'Nom de la commune',
 'UAI',
 "Nom de l'établissement",
 'Secteur',
 'IPS',
 'IPS national privé',
 'IPS national public',
 'IPS national',
 'IPS académique privé',
 'IPS académique public',
 'IPS académique',
 'IPS départemental privé',
 'IPS départemental public',
 'IPS départemental']

In [36]:
# 1 Define target columns to save memory
# target_columns based on business needs: Price, Location, Type, and Surface
target_ips_columns = [
    'Code INSEE de la commune', 'Secteur', 'IPS', 
    "Nom de l'établissement"
]

# Load the DVF file (using '|' separator as it's a .txt file from Government)
df_ips = pd.read_csv(
    '../data/raw/02_fr-en-ips-ecoles-ap2022.csv',
    # nrows=100, 
    usecols=target_ips_columns,
    sep=';', 
    #sep='|',
    low_memory=False
)

In [40]:
def clean_column_names(df):
    """
    Standardize DataFrame column names: 1. Convert to string / 2. Strip leading/trailing whitespaces
    3. Replace internal spaces with underscores / 4. Convert to lowercase
    """
    df.columns = (
        df.columns.astype(str)
                  .str.strip()
                  .str.replace(' ', '_', regex=False)
                  .str.lower()
    )
    return df

In [41]:
clean_column_names (df_ips)

,code_insee_de_la_commune,nom_de_l'établissement,secteur,ips
0,31147,ECOLE ELEMENTAIRE PUBLIQUE,public,NS
1,31157,ECOLE ELEMENTAIRE PUBLIQUE JEAN JAURES,public,115.6
2,31159,ECOLE ELEMENTAIRE PUBLIQUE,public,97.8
3,31160,ECOLE PRIMAIRE PUBLIQUE,public,130.3
4,31165,ECOLE ELEMENTAIRE PUBLIQUE JEAN DARGASSIES,public,106.2
...,...,...,...,...
97075,44143,ECOLE ELEMENTAIRE PUBLIQUE OUCHE DINIER,public,120.5
97076,44143,ECOLE ELEMENTAIRE PUBLIQUE ROGER SALENGRO,public,122.2
97077,44144,ECOLE PRIMAIRE PUBLIQUE ROBERT DOISNEAU,public,102.6
97078,44155,ECOLE PRIMAIRE PUBLIQUE JACQUES PREVERT,public,111.8
97079,44161,ECOLE PRIMAIRE PUBLIQUE ROBERT DOISNEAU,public,92.7

In [42]:
df_ips.to_csv('../data/clean/df_ips_processed.csv', index=False)

In [37]:
df_income_

,CODGEO,NBMEN21,NBPERS21,NBUC21,Q121,Q221,Q321,Q3_Q1,D121,D221,...,OPR6PTSA21,OPR6PCHO21,OPR6PBEN21,OPR6PPEN21,OPR6PPAT21,OPR6PPSOC21,OPR6PPFAM21,OPR6PPMINI21,OPR6PPLOGT21,OPR6PIMPOT21
0,1001,346,895,"590,8",s,25820,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
1,1002,115,266,"181,0",s,24480,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
2,1004,6855,15092,"10398,2",15800,21660,28430,12630,11890,14640,...,s,s,s,s,s,s,s,s,s,s
3,1005,800,2028,"1329,7",20010,24610,31180,11170,15560,18980,...,s,s,s,s,s,s,s,s,s,s
4,1006,51,107,"76,6",s,24210,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34924,97420,8593,23979,"15260,6",11970,17720,26400,14430,9060,11030,...,s,s,s,s,s,s,s,s,s,s
34925,97421,2472,6847,"4379,7",9860,13280,19240,9380,6810,9150,...,s,s,s,s,s,s,s,s,s,s
34926,97422,31239,79757,"52192,7",11440,16560,25020,13580,8660,10670,...,s,s,s,s,s,s,s,s,s,s
34927,97423,2505,7019,"4507,7",11480,16680,24240,12750,8570,10760,...,s,s,s,s,s,s,s,s,s,s
34928,97424,2142,5333,"3546,3",10580,13780,19730,9160,7690,9750,...,s,s,s,s,s,s,s,s,s,s

In [38]:
check_data_quality(df_income_)

Format du DataFrame (rows, cols): (34929, 732)

                Type  Manquants  % Manquants  Uniques  Doublons (par colonne)
CODGEO        object          0          0.0    34929                       0
NBMEN21          str          0          0.0     3814                   31115
NBPERS21         str          0          0.0     5749                   29180
NBUC21           str          0          0.0    13761                   21168
Q121             str          0          0.0     1232                   33697
...              ...        ...          ...      ...                     ...
OPR6PPSOC21      str          0          0.0        3                   34926
OPR6PPFAM21      str          0          0.0        3                   34926
OPR6PPMINI21     str          0          0.0        3                   34926
OPR6PPLOGT21     str          0          0.0        3                   34926
OPR6PIMPOT21     str          0          0.0        3                   34926

[732 rows x 5 columns]

In [39]:
df_income_.columns.tolist()

['CODGEO',
 'NBMEN21',
 'NBPERS21',
 'NBUC21',
 'Q121',
 'Q221',
 'Q321',
 'Q3_Q1',
 'D121',
 'D221',
 'D321',
 'D421',
 'D621',
 'D721',
 'D821',
 'D921',
 'RD',
 'S80S2021',
 'GI21',
 'PACT21',
 'PTSA21',
 'PCHO21',
 'PBEN21',
 'PPEN21',
 'PPAT21',
 'PPSOC21',
 'PPFAM21',
 'PPMINI21',
 'PPLOGT21',
 'PIMPOT21',
 'AGE1Q121',
 'AGE1Q221',
 'AGE1Q321',
 'AGE1Q3_Q1',
 'AGE1D121',
 'AGE1D221',
 'AGE1D321',
 'AGE1D421',
 'AGE1D621',
 'AGE1D721',
 'AGE1D821',
 'AGE1D921',
 'AGE1RD',
 'AGE1S80S2021',
 'AGE1GI21',
 'AGE1PACT21',
 'AGE1PTSA21',
 'AGE1PCHO21',
 'AGE1PBEN21',
 'AGE1PPEN21',
 'AGE1PPAT21',
 'AGE1PPSOC21',
 'AGE1PPFAM21',
 'AGE1PPMINI21',
 'AGE1PPLOGT21',
 'AGE1PIMPOT21',
 'AGE2Q121',
 'AGE2Q221',
 'AGE2Q321',
 'AGE2Q3_Q1',
 'AGE2D121',
 'AGE2D221',
 'AGE2D321',
 'AGE2D421',
 'AGE2D621',
 'AGE2D721',
 'AGE2D821',
 'AGE2D921',
 'AGE2RD',
 'AGE2S80S2021',
 'AGE2GI21',
 'AGE2PACT21',
 'AGE2PTSA21',
 'AGE2PCHO21',
 'AGE2PBEN21',
 'AGE2PPEN21',
 'AGE2PPAT21',
 'AGE2PPSOC21',
 'AGE2PPFAM21',
 'AGE2PPMINI21',
 'AGE2PPLOGT21',
 'AGE2PIMPOT21',
 'AGE3Q121',
 'AGE3Q221',
 'AGE3Q321',
 'AGE3Q3_Q1',
 'AGE3D121',
 'AGE3D221',
 'AGE3D321',
 'AGE3D421',
 'AGE3D621',
 'AGE3D721',
 'AGE3D821',
 'AGE3D921',
 'AGE3RD',
 'AGE3S80S2021',
 'AGE3GI21',
 'AGE3PACT21',
 'AGE3PTSA21',
 'AGE3PCHO21',
 'AGE3PBEN21',
 'AGE3PPEN21',
 'AGE3PPAT21',
 'AGE3PPSOC21',
 'AGE3PPFAM21',
 'AGE3PPMINI21',
 'AGE3PPLOGT21',
 'AGE3PIMPOT21',
 'AGE4Q121',
 'AGE4Q221',
 'AGE4Q321',
 'AGE4Q3_Q1',
 'AGE4D121',
 'AGE4D221',
 'AGE4D321',
 'AGE4D421',
 'AGE4D621',
 'AGE4D721',
 'AGE4D821',
 'AGE4D921',
 'AGE4RD',
 'AGE4S80S2021',
 'AGE4GI21',
 'AGE4PACT21',
 'AGE4PTSA21',
 'AGE4PCHO21',
 'AGE4PBEN21',
 'AGE4PPEN21',
 'AGE4PPAT21',
 'AGE4PPSOC21',
 'AGE4PPFAM21',
 'AGE4PPMINI21',
 'AGE4PPLOGT21',
 'AGE4PIMPOT21',
 'AGE5Q121',
 'AGE5Q221',
 'AGE5Q321',
 'AGE5Q3_Q1',
 'AGE5D121',
 'AGE5D221',
 'AGE5D321',
 'AGE5D421',
 'AGE5D621',
 'AGE5D721',
 'AGE5D821',
 'AGE5D921',
 'AGE5RD',
 'AGE5S80S2021',
 'AGE5GI21',
 'AGE5PACT21',
 'AGE5PTSA21',
 'AGE5PCHO21',
 'AGE5PBEN21',
 'AGE5PPEN21',
 'AGE5PPAT21',
 'AGE5PPSOC21',
 'AGE5PPFAM21',
 'AGE5PPMINI21',
 'AGE5PPLOGT21',
 'AGE5PIMPOT21',
 'AGE6Q121',
 'AGE6Q221',
 'AGE6Q321',
 'AGE6Q3_Q1',
 'AGE6D121',
 'AGE6D221',
 'AGE6D321',
 'AGE6D421',
 'AGE6D621',
 'AGE6D721',
 'AGE6D821',
 'AGE6D921',
 'AGE6RD',
 'AGE6S80S2021',
 'AGE6GI21',
 'AGE6PACT21',
 'AGE6PTSA21',
 'AGE6PCHO21',
 'AGE6PBEN21',
 'AGE6PPEN21',
 'AGE6PPAT21',
 'AGE6PPSOC21',
 'AGE6PPFAM21',
 'AGE6PPMINI21',
 'AGE6PPLOGT21',
 'AGE6PIMPOT21',
 'TME1Q121',
 'TME1Q221',
 'TME1Q321',
 'TME1Q3_Q1',
 'TME1D121',
 'TME1D221',
 'TME1D321',
 'TME1D421',
 'TME1D621',
 'TME1D721',
 'TME1D821',
 'TME1D921',
 'TME1RD',
 'TME1S80S2021',
 'TME1GI21',
 'TME1PACT21',
 'TME1PTSA21',
 'TME1PCHO21',
 'TME1PBEN21',
 'TME1PPEN21',
 'TME1PPAT21',
 'TME1PPSOC21',
 'TME1PPFAM21',
 'TME1PPMINI21',
 'TME1PPLOGT21',
 'TME1PIMPOT21',
 'TME2Q121',
 'TME2Q221',
 'TME2Q321',
 'TME2Q3_Q1',
 'TME2D121',
 'TME2D221',
 'TME2D321',
 'TME2D421',
 'TME2D621',
 'TME2D721',
 'TME2D821',
 'TME2D921',
 'TME2RD',
 'TME2S80S2021',
 'TME2GI21',
 'TME2PACT21',
 'TME2PTSA21',
 'TME2PCHO21',
 'TME2PBEN21',
 'TME2PPEN21',
 'TME2PPAT21',
 'TME2PPSOC21',
 'TME2PPFAM21',
 'TME2PPMINI21',
 'TME2PPLOGT21',
 'TME2PIMPOT21',
 'TME3Q121',
 'TME3Q221',
 'TME3Q321',
 'TME3Q3_Q1',
 'TME3D121',
 'TME3D221',
 'TME3D321',
 'TME3D421',
 'TME3D621',
 'TME3D721',
 'TME3D821',
 'TME3D921',
 'TME3RD',
 'TME3S80S2021',
 'TME3GI21',
 'TME3PACT21',
 'TME3PTSA21',
 'TME3PCHO21',
 'TME3PBEN21',
 'TME3PPEN21',
 'TME3PPAT21',
 'TME3PPSOC21',
 'TME3PPFAM21',
 'TME3PPMINI21',
 'TME3PPLOGT21',
 'TME3PIMPOT21',
 'TME4Q121',
 'TME4Q221',
 'TME4Q321',
 'TME4Q3_Q1',
 'TME4D121',
 'TME4D221',
 'TME4D321',
 'TME4D421',
 'TME4D621',
 'TME4D721',
 'TME4D821',
 'TME4D921',
 'TME4RD',
 'TME4S80S2021',
 'TME4GI21',
 'TME4PACT21',
 'TME4PTSA21',
 'TME4PCHO21',
 'TME4PBEN21',
 'TME4PPEN21',
 'TME4PPAT21',
 'TME4PPSOC21',
 'TME4PPFAM21',
 'TME4PPMINI21',
 'TME4PPLOGT21',
 'TME4PIMPOT21',
 'TME5Q121',
 'TME5Q221',
 'TME5Q321',
 'TME5Q3_Q1',
 'TME5D121',
 'TME5D221',
 'TME5D321',
 'TME5D421',
 'TME5D621',
 'TME5D721',
 'TME5D821',
 'TME5D921',
 'TME5RD',
 'TME5S80S2021',
 'TME5GI21',
 'TME5PACT21',
 'TME5PTSA21',
 'TME5PCHO21',
 'TME5PBEN21',
 'TME5PPEN21',
 'TME5PPAT21',
 'TME5PPSOC21',
 'TME5PPFAM21',
 'TME5PPMINI21',
 'TME5PPLOGT21',
 'TME5PIMPOT21',
 'TOL1Q121',
 'TOL1Q221',
 'TOL1Q321',
 'TOL1Q3_Q1',
 'TOL1D121',
 'TOL1D221',
 'TOL1D321',
 'TOL1D421',
 'TOL1D621',
 'TOL1D721',
 'TOL1D821',
 'TOL1D921',
 'TOL1RD',
 'TOL1S80S2021',
 'TOL1GI21',
 'TOL1PACT21',
 'TOL1PTSA21',
 'TOL1PCHO21',
 'TOL1PBEN21',
 'TOL1PPEN21',
 'TOL1PPAT21',
 'TOL1PPSOC21',
 'TOL1PPFAM21',
 'TOL1PPMINI21',
 'TOL1PPLOGT21',
 'TOL1PIMPOT21',
 'TOL2Q121',
 'TOL2Q221',
 'TOL2Q321',
 'TOL2Q3_Q1',
 'TOL2D121',
 'TOL2D221',
 'TOL2D321',
 'TOL2D421',
 'TOL2D621',
 'TOL2D721',
 'TOL2D821',
 'TOL2D921',
 'TOL2RD',
 'TOL2S80S2021',
 'TOL2GI21',
 'TOL2PACT21',
 'TOL2PTSA21',
 'TOL2PCHO21',
 'TOL2PBEN21',
 'TOL2PPEN21',
 'TOL2PPAT21',
 'TOL2PPSOC21',
 'TOL2PPFAM21',
 'TOL2PPMINI21',
 'TOL2PPLOGT21',
 'TOL2PIMPOT21',
 'TLD2Q121',
 'TLD2Q221',
 'TLD2Q321',
 'TLD2Q3_Q1',
 'TLD2D121',
 'TLD2D221',
 'TLD2D321',
 'TLD2D421',
 'TLD2D621',
 'TLD2D721',
 'TLD2D821',
 'TLD2D921',
 'TLD2RD',
 'TLD2S80S2021',
 'TLD2GI21',
 'TLD2PACT21',
 'TLD2PTSA21',
 'TLD2PCHO21',
 'TLD2PBEN21',
 'TLD2PPEN21',
 'TLD2PPAT21',
 'TLD2PPSOC21',
 'TLD2PPFAM21',
 'TLD2PPMINI21',
 'TLD2PPLOGT21',
 'TLD2PIMPOT21',
 'TLD3Q121',
 'TLD3Q221',
 'TLD3Q321',
 'TLD3Q3_Q1',
 'TLD3D121',
 'TLD3D221',
 'TLD3D321',
 'TLD3D421',
 'TLD3D621',
 'TLD3D721',
 'TLD3D821',
 'TLD3D921',
 'TLD3RD',
 'TLD3S80S2021',
 'TLD3GI21',
 'TLD3PACT21',
 'TLD3PTSA21',
 'TLD3PCHO21',
 'TLD3PBEN21',
 'TLD3PPEN21',
 'TLD3PPAT21',
 'TLD3PPSOC21',
 'TLD3PPFAM21',
 'TLD3PPMINI21',
 'TLD3PPLOGT21',
 'TLD3PIMPOT21',
 'TYM1Q121',
 'TYM1Q221',
 'TYM1Q321',
 'TYM1Q3_Q1',
 'TYM1D121',
 'TYM1D221',
 'TYM1D321',
 'TYM1D421',
 'TYM1D621',
 'TYM1D721',
 'TYM1D821',
 'TYM1D921',
 'TYM1RD',
 'TYM1S80S2021',
 'TYM1GI21',
 'TYM1PACT21',
 'TYM1PTSA21',
 'TYM1PCHO21',
 'TYM1PBEN21',
 'TYM1PPEN21',
 'TYM1PPAT21',
 'TYM1PPSOC21',
 'TYM1PPFAM21',
 'TYM1PPMINI21',
 'TYM1PPLOGT21',
 'TYM1PIMPOT21',
 'TYM2Q121',
 'TYM2Q221',
 'TYM2Q321',
 'TYM2Q3_Q1',
 'TYM2D121',
 'TYM2D221',
 'TYM2D321',
 'TYM2D421',
 'TYM2D621',
 'TYM2D721',
 'TYM2D821',
 'TYM2D921',
 'TYM2RD',
 'TYM2S80S2021',
 'TYM2GI21',
 'TYM2PACT21',
 'TYM2PTSA21',
 'TYM2PCHO21',
 'TYM2PBEN21',
 'TYM2PPEN21',
 'TYM2PPAT21',
 'TYM2PPSOC21',
 'TYM2PPFAM21',
 'TYM2PPMINI21',
 'TYM2PPLOGT21',
 'TYM2PIMPOT21',
 'TYM3Q121',
 'TYM3Q221',
 'TYM3Q321',
 'TYM3Q3_Q1',
 'TYM3D121',
 'TYM3D221',
 'TYM3D321',
 'TYM3D421',
 'TYM3D621',
 'TYM3D721',
 'TYM3D821',
 'TYM3D921',
 'TYM3RD',
 'TYM3S80S2021',
 'TYM3GI21',
 'TYM3PACT21',
 'TYM3PTSA21',
 'TYM3PCHO21',
 'TYM3PBEN21',
 'TYM3PPEN21',
 'TYM3PPAT21',
 'TYM3PPSOC21',
 'TYM3PPFAM21',
 'TYM3PPMINI21',
 'TYM3PPLOGT21',
 'TYM3PIMPOT21',
 'TYM4Q121',
 'TYM4Q221',
 'TYM4Q321',
 'TYM4Q3_Q1',
 'TYM4D121',
 'TYM4D221',
 'TYM4D321',
 'TYM4D421',
 'TYM4D621',
 'TYM4D721',
 'TYM4D821',
 'TYM4D921',
 'TYM4RD',
 'TYM4S80S2021',
 'TYM4GI21',
 'TYM4PACT21',
 'TYM4PTSA21',
 'TYM4PCHO21',
 'TYM4PBEN21',
 'TYM4PPEN21',
 'TYM4PPAT21',
 'TYM4PPSOC21',
 'TYM4PPFAM21',
 'TYM4PPMINI21',
 'TYM4PPLOGT21',
 'TYM4PIMPOT21',
 'TYM5Q121',
 'TYM5Q221',
 'TYM5Q321',
 'TYM5Q3_Q1',
 'TYM5D121',
 'TYM5D221',
 'TYM5D321',
 'TYM5D421',
 'TYM5D621',
 'TYM5D721',
 'TYM5D821',
 'TYM5D921',
 'TYM5RD',
 'TYM5S80S2021',
 'TYM5GI21',
 'TYM5PACT21',
 'TYM5PTSA21',
 'TYM5PCHO21',
 'TYM5PBEN21',
 'TYM5PPEN21',
 'TYM5PPAT21',
 'TYM5PPSOC21',
 'TYM5PPFAM21',
 'TYM5PPMINI21',
 'TYM5PPLOGT21',
 'TYM5PIMPOT21',
 'TYM6Q121',
 'TYM6Q221',
 'TYM6Q321',
 'TYM6Q3_Q1',
 'TYM6D121',
 'TYM6D221',
 'TYM6D321',
 'TYM6D421',
 'TYM6D621',
 'TYM6D721',
 'TYM6D821',
 'TYM6D921',
 'TYM6RD',
 'TYM6S80S2021',
 'TYM6GI21',
 'TYM6PACT21',
 'TYM6PTSA21',
 'TYM6PCHO21',
 'TYM6PBEN21',
 'TYM6PPEN21',
 'TYM6PPAT21',
 'TYM6PPSOC21',
 'TYM6PPFAM21',
 'TYM6PPMINI21',
 'TYM6PPLOGT21',
 'TYM6PIMPOT21',
 'OPR1Q121',
 'OPR1Q221',
 'OPR1Q321',
 'OPR1Q3_Q1',
 'OPR1D121',
 'OPR1D221',
 'OPR1D321',
 'OPR1D421',
 'OPR1D621',
 'OPR1D721',
 'OPR1D821',
 'OPR1D921',
 'OPR1RD',
 'OPR1S80S2021',
 'OPR1GI21',
 'OPR1PACT21',
 'OPR1PTSA21',
 'OPR1PCHO21',
 'OPR1PBEN21',
 'OPR1PPEN21',
 'OPR1PPAT21',
 'OPR1PPSOC21',
 'OPR1PPFAM21',
 'OPR1PPMINI21',
 'OPR1PPLOGT21',
 'OPR1PIMPOT21',
 'OPR2Q121',
 'OPR2Q221',
 'OPR2Q321',
 'OPR2Q3_Q1',
 'OPR2D121',
 'OPR2D221',
 'OPR2D321',
 'OPR2D421',
 'OPR2D621',
 'OPR2D721',
 'OPR2D821',
 'OPR2D921',
 'OPR2RD',
 'OPR2S80S2021',
 'OPR2GI21',
 'OPR2PACT21',
 'OPR2PTSA21',
 'OPR2PCHO21',
 'OPR2PBEN21',
 'OPR2PPEN21',
 'OPR2PPAT21',
 'OPR2PPSOC21',
 'OPR2PPFAM21',
 'OPR2PPMINI21',
 'OPR2PPLOGT21',
 'OPR2PIMPOT21',
 'OPR3Q121',
 'OPR3Q221',
 'OPR3Q321',
 'OPR3Q3_Q1',
 'OPR3D121',
 'OPR3D221',
 'OPR3D321',
 'OPR3D421',
 'OPR3D621',
 'OPR3D721',
 'OPR3D821',
 'OPR3D921',
 'OPR3RD',
 'OPR3S80S2021',
 'OPR3GI21',
 'OPR3PACT21',
 'OPR3PTSA21',
 'OPR3PCHO21',
 'OPR3PBEN21',
 'OPR3PPEN21',
 'OPR3PPAT21',
 'OPR3PPSOC21',
 'OPR3PPFAM21',
 'OPR3PPMINI21',
 'OPR3PPLOGT21',
 'OPR3PIMPOT21',
 'OPR4Q121',
 'OPR4Q221',
 'OPR4Q321',
 'OPR4Q3_Q1',
 'OPR4D121',
 'OPR4D221',
 'OPR4D321',
 'OPR4D421',
 'OPR4D621',
 'OPR4D721',
 'OPR4D821',
 'OPR4D921',
 'OPR4RD',
 'OPR4S80S2021',
 'OPR4GI21',
 'OPR4PACT21',
 'OPR4PTSA21',
 'OPR4PCHO21',
 'OPR4PBEN21',
 'OPR4PPEN21',
 'OPR4PPAT21',
 'OPR4PPSOC21',
 'OPR4PPFAM21',
 'OPR4PPMINI21',
 'OPR4PPLOGT21',
 'OPR4PIMPOT21',
 'OPR5Q121',
 'OPR5Q221',
 'OPR5Q321',
 'OPR5Q3_Q1',
 'OPR5D121',
 'OPR5D221',
 'OPR5D321',
 'OPR5D421',
 'OPR5D621',
 'OPR5D721',
 'OPR5D821',
 'OPR5D921',
 'OPR5RD',
 'OPR5S80S2021',
 'OPR5GI21',
 'OPR5PACT21',
 'OPR5PTSA21',
 'OPR5PCHO21',
 'OPR5PBEN21',
 'OPR5PPEN21',
 'OPR5PPAT21',
 'OPR5PPSOC21',
 'OPR5PPFAM21',
 'OPR5PPMINI21',
 'OPR5PPLOGT21',
 'OPR5PIMPOT21',
 'OPR6Q121',
 'OPR6Q221',
 'OPR6Q321',
 'OPR6Q3_Q1',
 'OPR6D121',
 'OPR6D221',
 'OPR6D321',
 'OPR6D421',
 'OPR6D621',
 'OPR6D721',
 'OPR6D821',
 'OPR6D921',
 'OPR6RD',
 'OPR6S80S2021',
 'OPR6GI21',
 'OPR6PACT21',
 'OPR6PTSA21',
 'OPR6PCHO21',
 'OPR6PBEN21',
 'OPR6PPEN21',
 'OPR6PPAT21',
 'OPR6PPSOC21',
 'OPR6PPFAM21',
 'OPR6PPMINI21',
 'OPR6PPLOGT21',
 'OPR6PIMPOT21']

In [43]:
# 1 Define target columns to save memory
# target_columns based on business needs: Price, Location, Type, and Surface
target_income_columns = [
    'CODGEO', 'NBMEN21', 'NBPERS21', 
    "NBUC21", 'Q221', 'PIMPOT21', 'TYM1Q221', 'TYM3Q221'
]

# Load the DVF file (using '|' separator as it's a .txt file from Government)
df_income = pd.read_csv(
    '../data/raw/02_FILO2021_DISP_COM.csv',
    # nrows=100, 
    usecols=target_income_columns,
    sep=';', 
    #sep='|',
    low_memory=False
)

In [46]:
df_income = df_income.rename(columns={
    'CODGEO': 'insee_code',
    'NBMEN21': 'nb_households',            # Nombre de foyers fiscaux (Ménages)
    'NBPERS21': 'nb_inhabitants',          # Le nombre total d'habitant
    'NBUC21': 'consumption_units',         # La pondération adulte/enfant (Standard INSEE)
    'Q221': 'median_income',               # Le revenu médian global de la zone
    'PIMPOT21': 'taxable_households_rate', # % de ménages payant l'impôt (Solvabilité)
    'TYM1Q221': 'solo_median_income',      # Revenu médian des célibataires
    'TYM3Q221': 'family_median_income'     # Revenu médian des couples avec enfants
})

In [47]:
df_income.to_csv('../data/clean/df_income_processed.csv', index=False)

In [ ]:
df_income